== Security

This chapter contains everything about security according to this project.

=== Authentication

==== Logging in

To log in against the whole service, simply request a `POST` on `/auth/login` with the following body:

.Login body[[loginBody]]
[source,json]
----
include::code/credentials.schema.json[]
----

If the request was successful, the server will return a JWT.
This JWT consists of a Base64 encoded header, a Base64 payload and a signature which is a hash calculated with the algorithmus given in the header from the rest.
All three parts are separated by a dot.

.Raw header of the claim
[source,json]
----
include::code/claimHeader.schema.json[]
----

.Raw payload of the claim
[source,json]
----
include::code/claimPayload.schema.json[]
----

NOTE: Read https://tools.ietf.org/html/rfc7519[this] or https://jwt.io[this] for further information.

==== Usage of the JWT

To use the token, it has to be added to the following HTTP header attribute: `Authorization: Bearer {JWT}`.

==== Renewal

To renew a token, simply do a request with a valid (not expired!) token on `/auth/refresh`.
The response will be the same as in the request with the credentials.

==== User Information

A request with the JWT header set to `/auth/self` will respond information about the user which corresponds to the JWT.
In case of an invalid JWT, the server will return a `HTTP 403`.

.User information response
[source,json]
----
include::code/self.schema.json[]
----

TIP: This request is also recommended to check if a JWT is valid

==== Change password

In order to change a password, one has to request a `POST` on `auth/password` with a <<loginBody, login body>>.

NOTE: Only admins are allowed to change other users password.

TIP: In order to create the first user, one may disable authentication in the config, insert a user and re-enable it.

==== Change Admin Status

In order to change an admin status, a request with the following `POST` has to be fired to `auth/admin`

[source,json]
----
include::code/admin.schema.json[]
----

NOTE: The issuer has to be admin in order to do this, or authentication has to be disabled.