== Database

This chapter describes, how the database works and how it is designed.

=== Model

.Database Model
[plantuml, database_model, svg]
....
@startuml

hide circle
skinparam linetype ortho

' entities

entity "addresses" as add {
  * **id : integer <<pk, nn, ai>>**
  --
  *city : text <<nn>>
  *post_code : text <<nn>>
  *<color:green>state_id : integer <<fk, nn>></color>
  *street : text <<nn>>
  *street_number : text <<nn>>
}

entity "state" as sta {
  * **id : integer <<pk, nn, ai>>**
  --
  *name : text <<nn, uq>>
  *deliveryPrice : real <<nn>>
}

entity "categories" as cat {
  * **id : integer <<pk, nn, ai>>**
  --
  *name : text <<nn, uq>>
  *<color:green>parent_id : integer <<fk>></color>
}

entity "orders" as ord {
  * **id : integer <<pk, nn, ai>>**
  --
  *<color:green>billing_address_id : integer <<fk>></color>
  *billing_date : datetime
  *company : text
  *date : datetime <<nn, uq>>
  *<color:green>delivery_address_id : integer <<fk, nn>></color>
  *email : text <<nn>>
  *first_name : text <<nn>>
  *last_name :  text <<nn>>
  *payed : datetime
  *reference_count : integer <<nn, uq>>
  *salutation : text
  *<color:green>items : item[] <<fk, nn>></color>
  *telephone: text
}

entity "items" as ite {
  * **id : integer <<pk, nn, ai>>**
  --
  *score_amount : integer <<nn>>
  *<color:green>score_id : integer <<fk, nn>></color>
}

entity "scores" as sco {
  * **id : integer <<pk, nn, ai>>**
  --
  *title : text <<nn>>
  *price : real <<nn>>
  *difficulty : integer <<nn>>
  *<color:green>category_id : integer <<fk, nn>></color>
}

entity "users" {
  * **email : text <<pk, nn>>**
  --
  *admin : integer <<nn>>
  *name : text <<nn>>
  *password : text <<nn>>
  *last_login : datetime <<nn>>
}

' relations

cat |o..|{ cat
cat |o..|{ sco
ord }|..|| add
ord }|..|| add
sta ||..|{ add
sco ||..|{ ite
ite }|..|| ord

@enduml
....