== Database

This chapter describes, how the database works and how it is designed.

=== Model

.Database Model
[plantuml, database_model, svg]
....
@startuml

hide circle
skinparam linetype ortho

' entities

entity "categories" as cat {
  * **id : integer <<pk, nn, ai>>**
  --
  *name : text <<nn, uq>>
  *<color:green>parentId : integer <<fk>></color>
}

entity "scores" as sco {
  * **id : integer <<pk, nn, ai>>**
  --
  *title : text <<nn>>
  *price : real <<nn>>
  *difficulty : integer <<nn>>
  *<color:green>categoryId : integer <<fk>></color>
}

entity "orders" as ord {
  * **id : integer <<pk, nn, ai>>**
  --
  *<color:green>billingAddressId : integer <<fk>></color>
  *company : text
  *date : integer <<nn>>
  *<color:green>deliveryAddressId : integer <<fk, nn>></color>
  *email : text <<nn>>
  *firstName : text <<nn>>
  *lastName :  text <<nn>>
  *payed : integer <<fk, nn>>
  *referenceCount : text <<nn>>
  *salutation : text
  *scoreAmount : integer <<nn>>
  *<color:green>scoreId : integer <<nn>></color>
  *telephone: text
}

entity "addresses" as add {
  * **id : integer <<pk, nn, ai>>**
  --
  *city : text <<nn>>
  *postCode : text <<nn>>
  *state : text <<nn>>
  *street : text <<nn>>
  *streetNumber : text <<nn>>
}

entity "users" {
  * **email : text <<pk, nn>>**
  --
  *admin : integer <<nn>>
  *name : text <<nn>
  *password : text <<nn>
  *lastChange : integer <<nn>>
  *lastLogin : integer <<nn>>
}

' relations

cat |o..|{ cat
cat |o..|{ sco
ord }|..|| add
ord }|..|| add
sco ||..|{ ord

@enduml
....